lovelace:
  mode: yaml
  resources:
    - url: /hacsfiles/vertical-stack-in-card/vertical-stack-in-card.js
      type: js
    - url: /hacsfiles/weather-card/weather-card.js
      type: module
    - url: /hacsfiles/circle-sensor-card/circle-sensor-card.js
      type: module
    - url: /hacsfiles/lovelace-layout-card/layout-card.js
      type: js
    - url: /hacsfiles/lovelace-card-tools/card-tools.js
      type: js
    - url: /hacsfiles/custom-header/custom-header.js
      type: module
    - url: /hacsfiles/lovelace-slider-entity-row/slider-entity-row.js
      type: js
    - url: /hacsfiles/mini-media-player/mini-media-player-bundle.js
      type: module
    - url: /hacsfiles/button-card/button-card.js
      type: module
    - url: /hacsfiles/simple-thermostat/simple-thermostat.js
      type: module
    - url: /hacsfiles/lovelace-xiaomi-vacuum-card/xiaomi-vacuum-card.js
      type: js
    - url: /hacsfiles/lovelace-fold-entity-row/fold-entity-row.js
      type: module
    - url: /hacsfiles/lovelace-toggle-lock-entity-row/toggle-lock-entity-row.js
      type: js
    - url: /hacsfiles/lovelace-gui-sandbox/gui-sandbox.js
      type: module
    - url: /hacsfiles/decluttering-card/decluttering-card.js
      type: module
    - url: /hacsfiles/lovelace-auto-entities/auto-entities.js
      type: module
    - url: /hacsfiles/lovelace-xiaomi-vacuum-map-card/xiaomi-vacuum-map-card.js
      type: module
    - url: /hacsfiles/banner-card/banner-card.js
      type: module
    - url: /hacsfiles/lovelace-card-mod/card-mod.js
      type: module
    - url: /hacsfiles/lovelace-swipe-navigation/swipe-navigation.js
      type: js
    - url: /hacsfiles/mini-graph-card/mini-graph-card-bundle.js
      type: module
    - url: /hacsfiles/lovelace-multiple-entity-row/multiple-entity-row.js
      type: module
    - url: /hacsfiles/miflora-card/miflora-card.js
      type: module