smoke_all:
  name: Smoke sensors
  icon: mdi:smoke-detector
  entities:
    - group.smoke_living_room

smoke_living_room:
  name: Living room
  icon: mdi:smoke-detector
  entities:
    - binary_sensor.smoke_sensor