water_all:
  name: Water sensors
  icon: mdi:water
  entities:
    - group.water_entrance
    - group.water_bathroom

water_entrance:
  name: Entrance
  icon: mdi:water
  entities:
    - binary_sensor.water_44 # Washing machine

water_bathroom:
  name: Bathroom
  icon: mdi:water
  entities:
    - binary_sensor.water_16 # Bathroom