door_all:
  name: All doors
  icon: mdi:door
  entities:
    - group.door_entrance
    - group.door_balcony

door_entrance:
  name: Front door
  icon: mdi:door
  entities:
    - binary_sensor.front_door_sensor # Xiaomi front door
    - binary_sensor.front_door # Ring front door

door_balcony:
  name: Balcony
  icon: mdi:door
  entities:
    - binary_sensor.balcony_sensor # Xiaomi balcony
    - binary_sensor.balcony # Ring balcony