alias: Guests bedroom - Alarm armed away
trigger:
  platform: state
  entity_id: alarm_control_panel.verdun_alarm
  to: 'armed_away'
action:
  service: light.turn_off
  entity_id: light.bedroom_guests_group
