type: custom:auto-entities
show_empty: false
card:
  type: glance
  title: 'Water & smoke sensors'
  show_header_toggle: false
filter:
  include:
    - entity_id: "binary_sensor.water*"
    - entity_id: "binary_sensor.smoke*"
    - entity_id: "group.smoke_*"
  exclude:
    - entity_id: "group.smoke_all"