basilic:
  sensors:
    moisture: sensor.slave_livingroom_basilic_moisture
    battery: sensor.slave_livingroom_basilic_battery
    conductivity: sensor.slave_livingroom_basilic_conductivity
  min_moisture: 20
  max_moisture: 60
  min_battery: 17
  min_conductivity: 500
  min_temperature: 15