bonsai_ficus:
  sensors:
    moisture: sensor.slave_livingroom_bonsai_ficus_moisture
    battery: sensor.slave_livingroom_bonsai_ficus_battery
    temperature: sensor.slave_livingroom_bonsai_ficus_temperature
    conductivity: sensor.slave_livingroom_bonsai_ficus_conductivity
    brightness: sensor.slave_livingroom_bonsai_ficus_light_intensity
  min_moisture: 20
  max_moisture: 60
  min_battery: 17
  min_conductivity: 350
  max_conductivity: 5000
  min_temperature: 15