pachira:
  sensors:
    moisture: sensor.slave_livingroom_pachira_moisture
    battery: sensor.slave_livingroom_pachira_battery
    temperature: sensor.slave_livingroom_pachira_temperature
    conductivity: sensor.slave_livingroom_pachira_conductivity
    brightness: sensor.slave_livingroom_pachira_intensity
  min_moisture: 20
  max_moisture: 60
  min_battery: 17
  min_conductivity: 350
  max_conductivity: 5000
  min_temperature: 15