alias: Bedroom - Remote wall on
initial_state: True
trigger:
  - platform: event
    event_type: app_daemon_remote
    event_data:
      entity_id: bedroom_wall
      state: "on"
      detail: "sr"
action:
  - service: light.turn_on
    data_template:
      entity_id: light.bedroom_group_color
      brightness_pct: 100
      color_temp: 500
  - service: light.turn_on
    data_template:
      entity_id: light.bedroom_group
      brightness_pct: 100

