alias: Living room - Remote on
initial_state: True
trigger:
  - platform: event
    event_type: app_daemon_remote
    event_data:
      entity_id: living_room
      state: "on"
      detail: "sr"
action:
  - service: light.turn_on
    data_template:
      entity_id: light.living_room_group
      brightness_pct: 100