alias: Alarm - Enable alarm auto
initial_state: True
trigger:
  - platform: state
    entity_id: group.family
    from: 'home'
    to: 'not_home'
  - platform: state
    entity_id: 'lock.front_door'
    to: 'locked'
condition:
  condition: and
  conditions:
    - condition: state
      entity_id: input_boolean.guest_mode
      state: 'off'
    - condition: template
      value_template: "{{ (not is_state('alarm_control_panel.verdun_alarm', 'armed_home')) and ((as_timestamp(now()) - as_timestamp(states.alarm_control_panel.verdun_alarm.last_changed)) > 300) }}"
    - condition: template
      value_template: "{{ (not is_state('alarm_control_panel.verdun_alarm', 'armed_away')) and ((as_timestamp(now()) - as_timestamp(states.alarm_control_panel.verdun_alarm.last_changed)) > 300) }}"
    # - condition: state
    #   entity_id: 'alarm_control_panel.verdun_alarm'
    #   state: 'disarmed'
    #   for:
    #     minutes: 5
    - condition: state
      entity_id: 'group.family'
      state: 'not_home'
action:
  - service: alarm_control_panel.alarm_arm_away
    entity_id: alarm_control_panel.verdun_alarm