alias: Alarm - Fix MQTT plugin and notify
initial_state: True
trigger:
  - platform: state
    entity_id: alarm_control_panel.verdun_alarm
    to: 'unavailable'
    for:
      seconds: 10
  - platform: time_pattern
    minutes: '/30'
    seconds: 0
condition:
  condition: and
  conditions:
    - condition: state
      entity_id: 'alarm_control_panel.verdun_alarm'
      state: 'unavailable'
action:
  - service: hassio.addon_restart
    data:
      addon: a98c085d_ring_mqtt
  - service: script.notify
    data:
      notify_id: everyone
      priority: 2
      title: "Alert"
      message: "Homeassistant is not able to handle Ring Alarm, connect ASAP."
  - delay:
      minutes: 1
      seconds: 30