alias: Alarm - Actions when alarm disabled and us absent
initial_state: True
trigger:
  - platform: state
    entity_id: alarm_control_panel.verdun_alarm
    to: 'disarmed'
action:
  - delay: 00:00:15
  - condition: state
    entity_id: 'group.family'
    state: 'not_home'
  - service: switch.turn_on
    entity_id: switch.alarm_toggle_blink