alias: Alarm - Check alarm
initial_state: True
trigger:
  - platform: state
    entity_id: group.family
    from: 'home'
    to: 'not_home'
    for:
      minutes: 5
  - platform: time_pattern
    hours: '/1'
    minutes: 0
    seconds: 0
condition:
  condition: and
  conditions:
    - condition: state
      entity_id: 'alarm_control_panel.verdun_alarm'
      state: 'disarmed'
    - condition: state
      entity_id: 'group.family'
      state: 'not_home'
action:
  - service: script.notify
    data:
      notify_id: everyone
      priority: 1
      title: "Alert"
      message: "The alarm is not on... Is it normal ?"