alias: Alarm - Actions when alarm enabled home
initial_state: True
trigger:
  - platform: state
    entity_id: alarm_control_panel.verdun_alarm
    from: 'disarmed'
    to: 'armed_home'
action:
  - service: switch.turn_on
    entity_id: switch.alarm_toggle_blink