alias: Camera - Captures files
initial_state: True
trigger:
  - platform: state
    entity_id: binary_sensor.blink_balcony_motion_detected
    to: 'on'
  - platform: state
    entity_id: binary_sensor.blink_entrance_motion_detected
    to: 'on'
  - platform: state
    entity_id: binary_sensor.blink_living_room_motion_detected
    to: 'on'
  - platform: state
    entity_id: binary_sensor.blink_cabane_papouille_motion_detected
    to: 'on'
condition:
  condition: or
  conditions:
    - condition: state
      entity_id: 'alarm_control_panel.verdun_alarm'
      state: 'armed_away'
    - condition: state
      entity_id: 'alarm_control_panel.verdun_alarm'
      state: 'armed_home'
action:
    - service: blink.blink_update
    - service: camera.snapshot
      data_template:
        entity_id: >-
          {% if trigger.entity_id == 'binary_sensor.blink_balcony_motion_detected' %} camera.blink_balcony
          {% elif trigger.entity_id == 'binary_sensor.blink_entrance_motion_detected' %} camera.blink_entrance
          {% elif trigger.entity_id == 'binary_sensor.blink_living_room_motion_detected' %} camera.blink_living_room
          {% elif trigger.entity_id == 'binary_sensor.blink_cabane_papouille_motion_detected' %} camera.blink_cabane_papouille
          {% endif%}
        filename: "captures/photos/{{ now().strftime('%Y%m%d_%H%M%S') }} - Blink - {{ trigger.to_state.attributes.friendly_name }}.jpg"
    - delay: 00:00:06
    - service: blink.blink_update
    - service: blink.save_video
      data:
        name: "{{trigger.to_state.attributes.friendly_name}}"
        filename: "captures/videos/{{ now().strftime('%Y%m%d_%H%M%S') }} - Blink - {{ trigger.to_state.attributes.friendly_name }}.mp4"