alias: Camera - Update blink picture
initial_state: True
trigger:
  - platform: time_pattern
    hours: '/1'
    minutes: 0
    seconds: 0
  - platform: event
    event_type: event_camera_blink_trigger_picture
action:
  - service: switch.turn_on
    entity_id: switch.camera_trigger_picture_living_room
  - delay:
      seconds: 15
  - service: switch.turn_on
    entity_id: switch.camera_trigger_picture_entrance
  - delay:
      seconds: 15
  - service: switch.turn_on
    entity_id: switch.camera_trigger_picture_balcony