alias: Camera - Captures files
initial_state: True
trigger:
  - platform: state
    entity_id: binary_sensor.blink_balcony_motion_detected
    to: 'on'
  - platform: state
    entity_id: binary_sensor.blink_entrance_motion_detected
    to: 'on'
  - platform: state
    entity_id: binary_sensor.blink_living_room_motion_detected
    to: 'on'
condition:
  condition: or
  conditions:
    - condition: state
      entity_id: 'alarm_control_panel.ring_alarm'
      state: 'armed_away'
    - condition: state
      entity_id: 'alarm_control_panel.ring_alarm'
      state: 'armed_home'
action:
    - service: blink.blink_update
    - service: camera.snapshot
      data_template:
        entity_id: >-
          {% if trigger.to_state.attributes.friendly_name == 'Balcony' %} camera.blink_balcony
          {% elif trigger.to_state.attributes.friendly_name == 'Entrance' %} camera.blink_entrance
          {% elif trigger.to_state.attributes.friendly_name == 'Living room (Blink)' %} camera.blink_living_room
          {% endif%}
        filename: "captures/photos/blink_photo_{{ trigger.to_state.attributes.friendly_name }}_{{ now().strftime('%Y%m%d_%H%M%S') }}.jpg"
    - delay: 00:00:06
    - service: blink.blink_update
    - service: blink.save_video
      data:
        name: "{{trigger.to_state.attributes.friendly_name}}"
        filename: "captures/videos/blink_video_{{ trigger.to_state.attributes.friendly_name }}_{{ now().strftime('%Y%m%d_%H%M%S') }}.mp4"