alias: House - Check light and turn off
initial_state: True
trigger:
  - platform: state
    entity_id: group.family
    from: 'home'
    to: 'not_home'
  - platform: time_pattern
    hours: '/1'
    minutes: 0
    seconds: 0
condition:
  condition: and
  conditions:
    - condition: state
      entity_id: 'light.all_inside_group'
      state: 'on'
    - condition: state
      entity_id: 'group.family'
      state: 'not_home'
action:
  - service: light.turn_off
    data:
      entity_id: light.all_inside_group