platform: template
lights:
  balcony:
    friendly_name: "Balcony"
    value_template: "{{ states('switch.balcony') }}"
    turn_on:
      service: switch.turn_on
      entity_id: switch.balcony
    turn_off:
      service: switch.turn_off
      entity_id: switch.balcony