alias: Living room - Alarm armed
trigger:
  - platform: state
    entity_id: alarm_control_panel.ring_alarm
    to: 'armed_away'
  - platform: state
    entity_id: alarm_control_panel.ring_alarm
    to: 'armed_home'
action:
  - service: light.turn_off
    entity_id: light.living_room_group
  - service: media_player.media_pause
    data:
      entity_id:
        - media_player.sonos_living_room # Sonos
  - service: media_player.turn_off
    data:
      entity_id:
        - media_player.living_room_tv # TV
  # - service: switch.turn_off
  #   entity_id: switch.harmony_tv
  # - service: light.turn_off # Moved into christmas.yaml
  #   data:
  #     entity_id: light.christmas_group