alias: Living room - Toggle AC
initial_state: True
trigger:
  - platform: event
    event_type: event_toggle_ac
condition:
  - condition: template
    value_template: "{{ state_attr('weather.dark_sky', 'temperature') | float > 25 }}"
action:
  - service_template: >
      {%- if is_state('climate.living_room', 'off') -%}
        climate.turn_on
      {%- else -%}
        climate.turn_off
      {%- endif -%}
    entity_id: climate.living_room