alias: Living room - Light mirror on
trigger:
  - platform: sun
    event: sunset
    offset: "-00:30:00"
condition:
  - condition: state
    entity_id: 'group.family'
    state: 'home'
action:
  - service: light.turn_on
    data:
      entity_id: light.mirror_living_room