alias: Living room - Light mirror off
trigger:
  - platform: state
    entity_id: alarm_control_panel.verdun_alarm
    to: 'armed_home'
action:
  - service: light.turn_off
    data:
      entity_id: light.mirror_living_room