alias: Bedroom - Remote laurent double click
initial_state: True
trigger:
  - platform: event
    event_type: app_daemon_remote
    event_data:
      entity_id: bedroom_laurent_switch
      state: "double_click"
condition:
  condition: and
  conditions:
    - condition: state
      entity_id: 'group.family'
      state: 'home'
action:
  - service: switch.toggle
    entity_id: switch.alarm_toggle_home