alias: Kitchen - Remote double click
initial_state: True
trigger:
  - platform: event
    event_type: app_daemon_remote
    event_data:
      entity_id: kitchen_switch
      state: "double_click"
action:
  - service: light.turn_off
    entity_id: 'light.kitchen_group'