alias: Bedroom - Remote giulia double click
initial_state: True
trigger:
  - platform: event
    event_type: app_daemon_remote
    event_data:
      entity_id: bedroom_giulia
      state: "double_click"
condition:
  condition: and
  conditions:
    - condition: state
      entity_id: 'group.family'
      state: 'home'
action:
  - service: light.turn_on
    entity_id: 'light.bedroom_group'
    data:
      brightness_pct: 100