alias: Bedroom - Remote cover single click
initial_state: True
trigger:
  - platform: event
    event_type: app_daemon_remote
    event_data:
      entity_id: bedroom_cover
      state: "single_click"
action:
  - service: cover.open_cover
    data:
      entity_id: 'cover.bedroom_1'