alias: Bedroom - Remote laurent single click
initial_state: True
trigger:
  - platform: event
    event_type: app_daemon_remote
    event_data:
      entity_id: bedroom_laurent_switch
      state: "single_click"
action:
  - service: light.turn_off
    data:
      entity_id: 'light.house_group'
  - service: alarm_control_panel.alarm_arm_home
    entity_id: alarm_control_panel.ring_alarm\
  - condition: time
    after: '08:00:00'
  - delay:
      seconds: 2
  - service: light.turn_on
    entity_id: 'light.bedroom_group'
    data:
      brightness_pct: 10