alias: Entrance - Alarm armed home
trigger:
  platform: state
  entity_id: alarm_control_panel.ring_alarm
  to: 'armed_home'
condition:
  condition: or
  conditions:
    - condition: state
      entity_id: sensor.season
      state: 'winter'
    - condition: state
      entity_id: sensor.season
      state: 'autumn'
action:
  - service: switch.turn_off
    entity_id: switch.ventilation