alias: Entrance - Alarm armed home
trigger:
  platform: state
  entity_id: alarm_control_panel.verdun_alarm
  to: 'armed_home'
condition:
  condition: or
  conditions:
    - condition: state
      entity_id: sensor.season
      state: 'winter'
    - condition: state
      entity_id: sensor.season
      state: 'autumn'
action:
  - condition: or
    conditions:
      - condition: time
        after: '20:00:00'
      - condition: time
        before: '06:00:00'
  - service: switch.turn_off
    entity_id: switch.ventilation