platform: template
switches:
  alarm_toggle_home:
    friendly_name: 'Alarm house armed home'
    value_template: "{{ is_state('alarm_control_panel.verdun_alarm', 'armed_home') }}"
    turn_on:
      - service: alarm_control_panel.alarm_arm_home
        entity_id: alarm_control_panel.alarm_arm_home
    turn_off:
      - service: alarm_control_panel.alarm_disarm
        entity_id: alarm_control_panel.verdun_alarm