platform: template
switches:
  camera_trigger_picture_balcony:
    friendly_name: 'Blink trigger picture'
    icon_template: mdi:camera
    value_template: "{{ is_state('script.camera_blink_trigger_camera', 'on') }}"
    turn_on:
      - service: script.turn_off
        data:
          entity_id: script.camera_blink_trigger_camera
      - service: script.camera_blink_trigger_camera
        data:
          entity_id: "camera.blink_balcony"
    turn_off:
  camera_trigger_picture_entrance:
    friendly_name: 'Blink trigger picture'
    icon_template: mdi:camera
    value_template: "{{ is_state('script.camera_blink_trigger_camera', 'on') }}"
    turn_on:
      - service: script.turn_off
        data:
          entity_id: script.camera_blink_trigger_camera
      - service: script.camera_blink_trigger_camera
        data:
          entity_id: "camera.blink_entrance"
    turn_off:
  camera_trigger_picture_living_room:
    friendly_name: 'Blink trigger picture'
    icon_template: mdi:camera
    value_template: "{{ is_state('script.camera_blink_trigger_camera', 'on') }}"
    turn_on:
      - service: script.turn_off
        data:
          entity_id: script.camera_blink_trigger_camera
      - service: script.camera_blink_trigger_camera
        data:
          entity_id: "camera.blink_living_room"
    turn_off:
  camera_trigger_picture_balcony_cabane:
    friendly_name: 'Blink trigger picture'
    icon_template: mdi:camera
    value_template: "{{ is_state('script.camera_blink_trigger_camera', 'on') }}"
    turn_on:
      - service: script.turn_off
        data:
          entity_id: script.camera_blink_trigger_camera
      - service: script.camera_blink_trigger_camera
        data:
          entity_id: "camera.blink_cabane_papouille"
    turn_off: