path: house.home
title: Home
icon: mdi:home
panel: false

badges:
  !include ../includes/_badges.yaml

cards:
  # - type: custom:gui-sandbox
  # Col 1
  - type: vertical-stack
    cards:
      - !include ../includes/footer_card.yaml
      # - type: entities
      #   title: Entities card sample
      #   show_header_toggle: true
      #   entities:
      #     - type: cast
      #       view: 0
      #       hide_if_unavailable: true
      # What is on - Always on top
      - !include ../includes/divers_notify_what_is_on.yaml
      # Lights group
      - !include ../includes/all/group_all_lights.yaml
      # - !include ../includes/opensky.yaml
      - !include ../includes/bottom-card.yaml
  # Col 2
  - type: vertical-stack
    cards:
      # TV's
      - type: entities
        title: 'TV''s'
        show_header_toggle: false
        entities:
          - switch.living_room_tv
          # - switch.living_room_plex
          - switch.living_room_netflix
          - switch.bedroom_tv
      # Divers
      - type: custom:vertical-stack-in-card
        cards:
          - type: entities
            title: 'House actions'
            show_header_toggle: false
            entities:
              - switch.ventilation
              - input_boolean.guest_mode
              - input_boolean.sleep_mode
              - input_select.cube_mode
          - type: conditional
            conditions:
              - entity: input_boolean.christmas_time
                state_not: "unavailable"
            card:
              type: entities
              entities:
                - input_boolean.christmas_time
      # Sonos
      - !include ../includes/all/group_all_media_player_sonos.yaml
      - !include ../includes/bottom-card.yaml
  # Col 3
  - type: vertical-stack
    cards:
      # Vacuum
      - !include ../includes/areas/living room/vacuum.yaml
      # Weather
      - !include ../includes/weather-card.yaml
      # - !include ../includes/divers_weather.yaml
      # Automations
      - type: custom:decluttering-card
        template: automation
        variables:
          - entity1: 'house*'
      - !include ../includes/bottom-card.yaml