path: house.security
title: Security
icon: mdi:shield
panel: false

badges:
  !include ../includes/_badges.yaml

cards:
  # Col 1
  - type: vertical-stack
    cards:
      - !include ../includes/footer_card.yaml
      - !include ../includes/areas/entrance/alarm_ring.yaml
      - type: glance
        entities: !include ../includes/entities/group_all.yaml
      # Camera
      - type: horizontal-stack
        cards:
          - type: custom:button-card
            name: Cameras
            tap_action:
              action: navigate
              navigation_path: /lovelace/house.cameras
      - type: horizontal-stack
        cards:
          - !include ../includes/areas/living room/camera_blink.yaml
          - !include ../includes/areas/living room/camera_foscam.yaml
      - type: horizontal-stack
        cards:
          - !include ../includes/areas/entrance/camera_blink.yaml
          - !include ../includes/areas/balcony/camera_blink.yaml
      - !include ../includes/all/group_all_door.yaml
      - !include ../includes/bottom-card.yaml
  # Col 2
  - type: vertical-stack
    cards:
      # Tracker
      - !include ../includes/security_tracker_all.yaml
      - !include ../includes/all/group_all_motion.yaml
      - !include ../includes/all/group_all_temperature.yaml
      - !include ../includes/bottom-card.yaml
  # Col 3
  - type: vertical-stack
    cards:
      - !include ../includes/all/group_all_water_smoke.yaml
      # Automations
      - type: custom:decluttering-card
        template: automation
        variables:
          - entity1: 'alarm*'
          - entity2: 'camera*'
          - entity3: 'security*'
          - entity4: 'person*'
      - !include ../includes/bottom-card.yaml