path: areas.living_room
title: Living room
icon: mdi:sofa
panel: false

badges:
  !include ../includes/_badges.yaml

cards:
  # Col 1
  - type: vertical-stack
    cards:
      - !include ../includes/footer_card.yaml
      # Lights
      - type: custom:vertical-stack-in-card
        cards:
          - type: entities
            entity: light.living_room_group
            title: Lights
            entities: !include ../includes/entities/lights_living-room.yaml
          - type: conditional
            conditions:
              - entity: light.christmas_group
                state_not: "unavailable"
            card:
              type: entities
              entities:
                - light.christmas_group
      # Switches
      - type: entities
        title: 'Actions'
        show_header_toggle: false
        entities:
          - scene.living_room_ambiance_tv
          - switch.living_room_tv
          - switch.living_room_netflix
          - type: custom:decluttering-card
            template: media_player
            variables:
              - entity: "sonos_living_room"
          - type: custom:decluttering-card
            template: media_player
            variables:
              - entity: "living_room_echo_dot"
              - tts_plateform: alexa
          - switch.vava_base
          # - type: divider
      - !include ../includes/bottom-card.yaml
  # Col 2
  - type: vertical-stack
    cards:
      - type: custom:decluttering-card
        template: mi_flora
        variables:
          - entity: 'slave_livingroom_living_room_bamboo'
          - title: 'Bamboo'
          - image: 'mi_flora_bamboo.jpg'
          - min_moisture: 20
          - max_moisture: 60
          - min_conductivity: 300
          - min_temperature: 12
      # Vacuum
      - !include ../includes/areas/living room/vacuum.yaml
      # AC
      - !include ../includes/areas/living room/climate_ac.yaml
      # Thermostat
      # - !include ../includes/areas/living room/climate_heat.yaml
      - !include ../includes/bottom-card.yaml
  # Col 3
  - type: vertical-stack
    cards:
      # Sensors
      - type: entities
        title: 'Sensors'
        show_header_toggle: false
        entities:
          - sensor.group_temperature_living_room
          - sensor.group_humidity_living_room
          - sensor.pressure_158d000245a7d5
          - binary_sensor.smoke_sensor_158d000257927b
          - type: divider
          - group.door_balcony
          - group.motion_living_room
      # Camera
      - type: horizontal-stack
        cards:
          - !include ../includes/areas/living room/camera_blink.yaml
          - !include ../includes/areas/living room/camera_foscam.yaml
      # Automations
      - type: custom:decluttering-card
        template: automation
        variables:
          - entity1: 'living_room*'
      - !include ../includes/bottom-card.yaml