path: areas.bedrooms.main
title: Main bedroom
icon: mdi:bed-king
panel: false

badges:
  !include ../includes/_badges.yaml

cards:
  # Col 1
  - type: vertical-stack
    cards:
      - !include ../includes/footer_card.yaml
      # Lights
      - type: entities
        entity: light.bedroom_group
        title: Lights
        entities: !include ../includes/entities/lights_main-bedroom.yaml
      # Alarm house
      - !include ../includes/areas/entrance/alarm_ring.yaml
      - !include ../includes/bottom-card.yaml
  # Col 2
  - type: vertical-stack
    cards:
      # Switches
      - type: entities
        title: 'Actions'
        show_header_toggle: false
        entities:
          - type: custom:decluttering-card
            template: media_player
            variables:
              - entity: "nvidia_shield"
          - type: divider
          - cover.bedroom_1
          - !include ../includes/areas/bedrooms/main/switch_soma.yaml
          - switch.sonoff_100048cb54
          - type: divider
          - type: custom:decluttering-card
            template: media_player
            variables:
              - entity: "sonos_bedroom"
          - type: custom:decluttering-card
            template: media_player
            variables:
              - entity: "bedroom_dot"
              - tts_plateform: "alexa"
          - !include ../includes/bottom-card.yaml
  # Col 3
  - type: vertical-stack
    cards:
      # Sensors
      - type: entities
        title: 'Sensors'
        show_header_toggle: false
        entities:
          - group.safe_bedroom
          - sensor.group_light_level_bedroom
          - sensor.group_temperature_bedroom
          - sensor.group_humidity_bedroom
          - type: divider
          - group.motion_bedroom
      # Thermostat
      # - !include ../includes/areas/bedrooms/main/climate_heat.yaml
      # Automations
      - type: custom:decluttering-card
        template: automation
        variables:
          - entity1: 'bedroom_*'
          - entity2: 'corridor*'
      - !include ../includes/bottom-card.yaml