path: areas.bedrooms.guests
title: Guest bedroom
icon: mdi:bed-queen
panel: false

badges:
  !include ../includes/_badges.yaml

cards:
  # Col 1
  - type: vertical-stack
    cards:
      - !include ../includes/footer_card.yaml
      # Lights
      - type: entities
        entity: light.bedroom_guests_group
        title: Lights
        entities: !include ../includes/entities/lights_guests-bedroom.yaml
      # Alarm house
      - !include ../includes/areas/entrance/alarm_ring.yaml
      - !include ../includes/bottom-card.yaml
  # Col 2
  - type: vertical-stack
    cards:
      # Lavande
      - type: custom:decluttering-card
        template: mi_flora
        variables:
          - entity: 'lavande'
          - title: 'Lavande'
          - image: 'mi_flora_lavande.jpg'
      # Sensors
      - type: entities
        title: 'Sensors'
        show_header_toggle: false
        entities:
          - sensor.group_light_level_guests_bedroom
          - sensor.group_temperature_guests_bedroom
          - type: divider
          - group.motion_guests_bedroom
      # Automations
      - type: custom:decluttering-card
        template: automation
        variables:
          - entity1: 'guests_*'
          - entity2: 'corridor*'
      - !include ../includes/bottom-card.yaml