path: areas.balcony
title: Balcony
icon: mdi:grill
panel: false

badges:
  !include ../includes/_badges.yaml

cards:
  # Col 1
  - type: vertical-stack
    cards:
      - !include ../includes/footer_card.yaml
      # Lights
      - type: entities
        entity: light.balcony_group
        title: Lights
        entities: !include ../includes/entities/lights_balcony.yaml
      # Pot mi flora
      - type: custom:decluttering-card
        template: mi_flora
        variables:
          - entity: 'slave_livingroom_basilic'
          - title: 'Basilic'
          - image: 'mi_flora_basilic.jpg'
          - min_moisture: 20
          - max_moisture: 60
          - min_conductivity: 300
          - min_temperature: 12
      # Caisse basilic
      - type: custom:decluttering-card
        template: mi_flora
        variables:
          - entity: 'slave_livingroom_caisse_basilic'
          - title: 'Caisse basilic'
          - image: 'mi_flora_basilic.jpg'
          - min_moisture: 20
          - max_moisture: 60
          - min_conductivity: 300
          - min_temperature: 12
      # Camera
      - type: horizontal-stack
        cards:
          - !include ../includes/areas/balcony/camera_blink.yaml
      - !include ../includes/bottom-card.yaml
  # Col 2
  - type: vertical-stack
    cards:
      # Sensors
      - type: entities
        title: 'Sensors'
        show_header_toggle: false
        entities:
          - sensor.group_temperature_balcony
          - type: divider
          - group.door_balcony
          - group.motion_balcony
      # Automations
      - type: custom:decluttering-card
        template: automation
        variables:
          - entity1: 'balcony_*'
      - !include ../includes/bottom-card.yaml