type: custom:decluttering-card
template: monitoring
variables:
  - title: 'VM monitoring'
  - graph1_entity: 'processor_use'
  - graph2_entity: 'unavailable'
  - bar1_entity: 'disk_use_percent'
  - bar1_color: '#00ba6a'
  - bar2_entity: 'memory_use_percent'
  - other_entities:
    - sensor.last_boot
