type: custom:decluttering-card
template: monitoring
variables:
  - title: 'Syno monitoring'
  - graph1_entity: 'synology_4b_cpu_load_total'
  - graph2_entity: 'unavailable'
  - bar1_entity: 'synology_4b_volume_1_used_space'
  - bar1_color: '#00ba6a'
  - bar2_entity: 'sensor.synology_4b_memory_usage_real'
  - other_entities:
    - sensor.synology_4b_volume_1_status
    - sensor.synology_4b_volume_1_volume_used
    - sensor.synology_4b_network_up
