type: vertical-stack
cards:
  - type: entities
    title: NUC monitoring
    show_header_toggle: false
    entities:
      - type: custom:auto-entities
        show_empty: false
        filter:
          include:
            - entity_id: "script.pc_nuc*"
        card:
          type: custom:fold-entity-row
          head:
            type: section
            label: 'Scripts ⚠️'
          padding: 0
          group_config:
            secondary_info: last-changed
      - type: custom:auto-entities
        show_empty: false
        filter:
          include:
            - entity_id: "binary_sensor.pc_nuc*"
            - entity_id: "sensor.pc_nuc*"
          exclude:
            - entity_id: sensor.pc_nuc_hdd_usage_d
            - entity_id: sensor.pc_nuc_hdd_usage_c
            - entity_id: sensor.pc_nuc_ram_usage
            - entity_id: sensor.pc_nuc_cpu_usage
        card:
          type: custom:fold-entity-row
          head:
            type: section
            label: 'Other sensors'
          padding: 0
          group_config:
            secondary_info: last-changed
      - type: custom:decluttering-card
        template: monitoring
        variables:
          - title: 'Syno monitoring'
          - graph1_entity: 'pc_nuc_cpu_usage'
          - graph2_entity: 'unavailable'
          - bar1_entity: 'pc_nuc_hdd_usage_c'
          - bar1_color: '#00ba6a'
          - bar2_entity: 'pc_nuc_hdd_usage_d'
          - bar2_color: '#00ba6a'
          - bar3_entity: 'pc_nuc_ram_usage'
          - other_entities:
            - binary_sensor.pc_nuc_connected
