type: custom:vertical-stack-in-card
cards:
  - type: glance
    title: Syno monitoring
    entities:
      - sensor.synology_status_volume_1
      - sensor.synology_used_space_volume_1
      - sensor.synology_network_up
      # Weblink not working yet but it suppposed to arrive. See weblink in glance
      - entity: sensor.time
        name: Synology
        icon: mdi:harddisk
        tap_action:
          action: url
          url_path: !secret global_url_synology
  - type: horizontal-stack
    cards:
      - type: gauge
        entity: sensor.synology_volume_used_volume_1
        title: Disk
        unit_of_measurement: '%'
        min: 0
        max: 100
        severity:
          yellow: 45
          green: 10
          red: 90
      - type: gauge
        entity: sensor.synology_cpu_load_total
        title: CPU
        unit_of_measurement: '%'
        min: 0
        max: 100
        severity:
          yellow: 45
          green: 10
          red: 90
      - type: gauge
        entity: sensor.synology_memory_usage_real
        title: RAM
        unit_of_measurement: '%'
        min: 0
        max: 100
        severity:
          yellow: 45
          green: 10
          red: 90