type: custom:decluttering-card
template: monitoring
variables:
  - title: 'AD-Guard monitoring'
  - graph1_entity: 'adguard_average_processing_speed'
  - graph2_entity: 'adguard_dns_queries'
  - bar1_entity: 'adguard_dns_queries_blocked_ratio'
  # - bar1_color: '#00ba6a'
  - bar2_entity: ''
  - other_entities:
    - switch.adguard_filtering
    - sensor.adguard_dns_queries_blocked
