default:
  - entity: 'plant.bansai'
  - title: 'Living room bonsai Japanese'
  - image: 'mi_flora.jpg'

card:
  type: conditional
  conditions:
    - entity: 'plant.[[entity]]'
      state_not: "unavailable"
  card:
    type: plant-status
    entity: 'plant.[[entity]]'
    name: '[[title]]'
    # type: custom:miflora-card
    # title: '[[title]]'
    # image: img/[[image]]
    # min_moisture: '[[min_moisture]]'
    # max_moisture: '[[max_moisture]]'
    # min_conductivity: '[[min_conductivity]]'
    # min_temperature: '[[min_temperature]]'
    # entities:
    #   - entity: '[[entity]].attributes.moisture'
    #     type: moisture
    #   - entity: '[[state_attr("plant.bonsai_ficus", "light_intensity")]]'
    #     type: intensity
    #     name: Light
    #   - entity: plant.bonsai_ficus.attributes.temperature
    #     type: temperature
    #   - entity: '[[ plant.bonsai_ficus.attributes.conductivity ]]'
    #     type: conductivity
    #     name: Fertility
    #   - entity: '[[[ state_attr("plant.bonsai_ficus", "battery") ]]]'
    #     type: battery