default:
  - entity: 'living_room_bamboo'
  - title: 'Living room Bamboo'
  - image: 'mi_flora.jpg'
  - min_moisture: 15
  - max_moisture: 60
  - min_conductivity: 350
  - min_temperature: 12

card:
  type: conditional
  conditions:
    - entity: 'sensor.[[entity]]_moisture'
      state_not: "unavailable"
  card:
    type: custom:miflora-card
    title: '[[title]]'
    image: img/[[image]]
    min_moisture: '[[min_moisture]]'
    max_moisture: '[[max_moisture]]'
    min_conductivity: '[[min_conductivity]]'
    min_temperature: '[[min_temperature]]'
    entities:
      - entity: sensor.[[entity]]_moisture
        type: moisture
      - entity: sensor.[[entity]]_light_intensity
        type: intensity
      - entity: sensor.[[entity]]_temperature
        type: temperature
      - entity: sensor.[[entity]]_conductivity
        type: conductivity
        name: Fertility
      - entity: sensor.[[entity]]_battery
        type: battery