alias: Bathroom - Alarm armed away
trigger:
  platform: state
  entity_id: alarm_control_panel.verdun_alarm
  to: 'armed_away'
action:
  - service: light.turn_off
    entity_id: light.bathroom_group
  - service: media_player.media_pause
    data:
      entity_id:
        - media_player.sonos_bathroom # Sonos