alias: Bathroom - Lights on
initial_state: True
trigger:
  - platform: state
    entity_id: group.motion_bathroom
    to: 'on'
  - platform: state
    entity_id: input_number.light_variable_brightness
condition:
  condition: and
  conditions:
    - condition: template
      value_template: "{{ not is_state('alarm_control_panel.verdun_alarm', 'armed_away') }}"
    - condition: template
      value_template: "{{ (trigger.entity_id == 'group.motion_bathroom') and is_state('light.bathroom_group', 'off') }}"
    - condition: time
      after: '06:50:00'
action:
  - service: 'light.turn_on'
    entity_id: 'light.bathroom_group'
    data_template:
      brightness_pct: >-
        {% if (now().hour < 7) %} 40
        {% elif (now().hour < 22) %} 100
        {% elif (now().hour < 23) or ((now().hour == 23) and (now().minute < 45)) %} 40
        {% else %} 0
        {% endif%}