alias: Security - Safe opened while not there
initial_state: True
trigger:
  - platform: state
    entity_id: group.safe_bedroom
    to: 'on'
condition:
  condition: or
  conditions:
    - condition: state
      entity_id: 'group.family'
      state: 'not_home'
    - condition: template
      value_template: "{{ not is_state('alarm_control_panel.verdun_alarm', 'disarmed') }}"
action:
  - service: script.notify
    data:
      notify_id: everyone
      priority: 2
      persistent_notification: True
      persistent_notification_id: hass_entitie_safe_open
      title: "Alert"
      message: The safe has been opened !