alias: Bedroom - Alarm armed away open cover
trigger:
  - platform: state
    entity_id: alarm_control_panel.verdun_alarm
    to: 'armed_away'
condition:
  - condition: time
    before: '17:00:00'
  - condition: template
    value_template: "{{ state_attr('weather.dark_sky', 'temperature') | float < 10 }}"
action:
  - service: cover.open_cover
    data:
      entity_id: cover.bedroom_1