alias: Bedroom - Lights on
initial_state: True
trigger:
  - platform: state
    entity_id: 'group.motion_bedroom'
    to: 'on'
  - platform: state
    entity_id: input_number.light_variable_brightness
condition:
  condition: and
  conditions:
    - condition: template
      value_template: "{{ not is_state('alarm_control_panel.ring_alarm', 'armed_away') }}"
    - condition: template
      value_template: "{{ (trigger.entity_id == 'group.motion_bedroom') and is_state('light.bedroom_group', 'off') }}"
    - condition: state
      entity_id: input_boolean.sleep_mode
      state: 'off'
    - condition: time
      after: '17:00:00'
      before: '22:45:00'
action:
  - service: 'light.turn_on'
    entity_id: 'light.bedroom_group'
    data_template:
      brightness_pct: >-
        {% if (now().hour < 8) %} 10
        {% elif (now().hour < 10) %} 20
        {% elif (now().hour < 21) %} 100
        {% elif (now().hour < 22) %} 30
        {% elif (now().hour < 23) or ((now().hour == 23) and (now().minute < 45)) %} 10
        {% else %} 0
        {% endif%}