alias: Bedroom - Remote giulia
initial_state: True
trigger:
  - device_id: c86cb94ab5c94e94a105caef941ca19d
    domain: hue
    platform: device
    type: remote_button_short_press
    subtype: button_1
action:
  - service: alarm_control_panel.alarm_arm_home
    entity_id: alarm_control_panel.ring_alarm