alias: Bedroom - Remote laurent double click
initial_state: True
trigger:
  platform: event
  event_type: xiaomi_aqara.click
  event_data:
    entity_id: binary_sensor.switch_158d000253d163
    click_type: double
condition:
  condition: and
  conditions:
    - condition: state
      entity_id: 'group.family'
      state: 'home'
action:
  - service: switch.toggle
    entity_id: switch.alarm_toggle_home