alias: Bedroom - Remote laurent
initial_state: True
trigger:
  - device_id: 46c0befd6b29498cacc2b95a3c8f61ea
    domain: hue
    platform: device
    type: remote_button_short_release
    subtype: turn_off
  - device_id: 46c0befd6b29498cacc2b95a3c8f61ea
    domain: hue
    platform: device
    type: remote_button_long_release
    subtype: turn_off
action:
  - service: light.turn_off
    entity_id: light.kitchen_led