alias: Bedroom - Remote laurent single click
initial_state: True
trigger:
  platform: event
  event_type: xiaomi_aqara.click
  event_data:
    entity_id: binary_sensor.switch_158d000253d163
    click_type: single
action:
  - service: light.turn_off
    data:
      entity_id: 'light.house_group'
  - service: alarm_control_panel.alarm_arm_home
    entity_id: alarm_control_panel.ring_alarm
  - delay:
      seconds: 2
  - service: light.turn_on
    entity_id: 'light.bedroom_group'
    data:
      brightness_pct: 10